// Generated by CoffeeScript 1.12.2
(function() {
  alert("Welcome to Cofee fun!");;
  var height, maxDwarfism, minAcromegaly, normalHeight;

  maxDwarfism = 147;

  minAcromegaly = 213;

  height = 180;

  normalHeight = (maxDwarfism < height && height < minAcromegaly);

  alert(normalHeight);

}).call(this);
