// Generated by CoffeeScript 1.12.2
(function() {
  alert("Welcome to Cofee fun!");;
  var height, i, maxDwarfism, minAcromegaly, normalHeight, x;

  maxDwarfism = 147;

  minAcromegaly = 213;

  height = 180;

  normalHeight = (maxDwarfism < height && height < minAcromegaly);

  alert(normalHeight);

  for (x = i = 1; i <= 50; x = ++i) {
    console.log(x);
  }

}).call(this);
